import React, { useEffect, useState } from "react";
import { FormField, Card, Loader } from "../components";
import axios from "axios";

const RenderCards = ({ data, title }) => {
    if (data?.length > 0) {
        return data?.map((post) => <Card key={post._id} {...post} />);
    }
    return (
        <h2 className="mt-5 font-bold text-white text-xl uppercase">
            {title}
        </h2>
    );
};

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState("");
    const [searchResult, setSearchResult] = useState("");

    useEffect(() => {
        try {
            let callImage = async () => {
                let resp = await axios.get(
                    `${import.meta.env.VITE_BASE_URL}/allposts`
                );
                console.log(resp?.data?.posts);
                setAllPosts(resp?.data?.posts);
            };
            callImage();
        } catch (error) {
            console.log(error);
        }
    }, []);

    const handleSearch = (e) => {
        setSearchText(e.target.value);
        const searchTextResult = allPosts.filter(
            (item) =>
                item.name.toLowerCase().includes(searchText.toLowerCase()) ||
                item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        setSearchResult(searchTextResult);
    };

    return (
        <>
            <section className="max-w-8xl mx-auto  ">
                <div>
                    <h1 className="font-extrabold text-[#222328] text-[32px]  ">
                        {" "}
                        The Community Showcase{" "}
                    </h1>
                    <p className="mt-2 text-[#666e75] text-[16px] max-2-[500px] ">
                        Browse through a collection of imaginative and visually
                        stunning images generated by WALL-E AI
                    </p>
                </div>
                <div className="mt-16">
                    <FormField
                        labelName={"search post"}
                        type="text"
                        name="search"
                        placeholder="search posts"
                        value={searchText}
                        handleChange={handleSearch}
                    />
                </div>
                <div className="mt-16">
                    {loading ? (
                        <div className="flex justify-center items-center ">
                            {" "}
                            <Loader />{" "}
                        </div>
                    ) : (
                        <>
                            {searchText && (
                                <h2 className="font-medium text-[#666e75] text-sm mb-3 ">
                                    Showing results for{" "}
                                    <span className="text-[#222328] ">
                                        {" "}
                                        {searchText}{" "}
                                    </span>
                                </h2>
                            )}

                            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3 ">
                                {searchText ? (
                                    <RenderCards
                                        data={searchResult}
                                        title="no search result found"
                                    />
                                ) : (
                                    <>
                                        <RenderCards
                                            data={allPosts}
                                            title="No posts found"
                                        />
                                    </>
                                )}
                            </div>
                        </>
                    )}
                </div>
            </section>
        </>
    );
};

export default Home;
